const fs = require('fs');

const hashAdmin = '$2b$12$jq.47cjE/mxj4odKTENlXubqQ3BNXoNwmVLccK1S1Rl1pkG6zd3yK';

const users = [
  {
    id: 'admin-principal',
    username: 'admin',
    email: 'admin@minuta.com',
    passwordHash: hashAdmin,
    firstName: 'Administrador',
    lastName: 'Principal',
    documento: '1020304050',
    telefono: '3109988776',
    role: 'admin',
    turno: 'Administración (08:00 - 17:00)',
    puesto: 'Oficina de Administración',
    diasLaborales: 'Lunes a Viernes',
    isActive: true,
    emailVerified: true,
    twoFactorEnabled: false,
    createdAt: new Date().toISOString()
  },
  {
    id: 'sup-rodrigo',
    username: 'supervisor.pineda',
    email: 'supervisor@minuta.com',
    passwordHash: hashAdmin,
    firstName: 'Rodrigo',
    lastName: 'Pineda',
    documento: '79845120',
    telefono: '3158877441',
    role: 'supervisor',
    turno: 'Turno Rotativo / Control',
    puesto: 'Supervisión General & Rondas',
    diasLaborales: 'Lunes a Sábado',
    isActive: true,
    emailVerified: true,
    twoFactorEnabled: false,
    createdAt: new Date().toISOString()
  },
  {
    id: 'gua-carlos',
    username: 'guarda.mendez',
    email: 'carlos.mendez@seguridad.com',
    passwordHash: hashAdmin,
    firstName: 'Carlos Eduardo',
    lastName: 'Méndez',
    documento: '1014258963',
    telefono: '3201144778',
    role: 'guarda',
    turno: 'Turno Mañana (06:00 - 14:00)',
    puesto: 'Portería Principal Peatonal',
    diasLaborales: 'Lunes a Domingo (Descanso Miércoles)',
    isActive: true,
    emailVerified: true,
    twoFactorEnabled: false,
    createdAt: new Date().toISOString()
  },
  {
    id: 'gua-jhon',
    username: 'guarda.beltran',
    email: 'jhon.beltran@seguridad.com',
    passwordHash: hashAdmin,
    firstName: 'Jhon Jairo',
    lastName: 'Beltrán',
    documento: '1018965412',
    telefono: '3114455889',
    role: 'guarda',
    turno: 'Turno Mañana (06:00 - 14:00)',
    puesto: 'Acceso Vehicular & Parqueaderos',
    diasLaborales: 'Lunes a Domingo (Descanso Jueves)',
    isActive: true,
    emailVerified: true,
    twoFactorEnabled: false,
    createdAt: new Date().toISOString()
  },
  {
    id: 'gua-nelson',
    username: 'guarda.morales',
    email: 'nelson.morales@seguridad.com',
    passwordHash: hashAdmin,
    firstName: 'Nelson Javier',
    lastName: 'Morales',
    documento: '1022334455',
    telefono: '3167788990',
    role: 'guarda',
    turno: 'Turno Tarde (14:00 - 22:00)',
    puesto: 'Portería Principal & Paquetería',
    diasLaborales: 'Lunes a Domingo (Descanso Lunes)',
    isActive: true,
    emailVerified: true,
    twoFactorEnabled: false,
    createdAt: new Date().toISOString()
  },
  {
    id: 'gua-andres',
    username: 'guarda.quintana',
    email: 'andres.quintana@seguridad.com',
    passwordHash: hashAdmin,
    firstName: 'Andrés Felipe',
    lastName: 'Quintana',
    documento: '1033669988',
    telefono: '3182233445',
    role: 'guarda',
    turno: 'Turno Tarde (14:00 - 22:00)',
    puesto: 'Monitoreo de Cámaras & Rondas',
    diasLaborales: 'Lunes a Domingo (Descanso Martes)',
    isActive: true,
    emailVerified: true,
    twoFactorEnabled: false,
    createdAt: new Date().toISOString()
  },
  {
    id: 'gua-wilson',
    username: 'guarda.cardenas',
    email: 'wilson.cardenas@seguridad.com',
    passwordHash: hashAdmin,
    firstName: 'Wilson Darío',
    lastName: 'Cárdenas',
    documento: '71258963',
    telefono: '3149900112',
    role: 'guarda',
    turno: 'Turno Noche (22:00 - 06:00)',
    puesto: 'Vigilancia Nocturna & Perímetro',
    diasLaborales: 'Lunes a Domingo (Descanso Viernes)',
    isActive: true,
    emailVerified: true,
    twoFactorEnabled: false,
    createdAt: new Date().toISOString()
  }
];

fs.writeFileSync('c:/Users/kevin/Desktop/PROYECTOS/minuta/backend/users.json', JSON.stringify(users, null, 2));
console.log(`✓ Creados ${users.length} usuarios y vigilantes con horarios y puestos`);